a = 1 #integer
b = 2.5 #float
c = "aavi" #string
d = True #boolean
e = False #boolean
f = None #none type 
g = [1, 2, 3, 4] #list
h = (1, 2, 3, 4) #tuple
i = {1, 2, 3, 4} #set
j = {"name": "aavi", "age": 26} #dictionary
k = b"aavi" #bytes
l = bytearray(5) #bytearray
m = memoryview(bytes(5)) #memoryview 
n = complex(1, 2) #complex number
o = range(5) #range
p = frozenset([1, 2, 3, 4]) #frozenset
q = type(a) #type
r = isinstance(a, int) #isinstance 
s = id(a) #id
t = hash(a) #hash
w = len(g) #length 
u = max(g) #maximum
v = min(g) #minimum 
x = sum(g) #sum
y = sorted(g) #sorted 
z = reversed(g) #reversed 
